name: Build and push to Docker Hub
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & tag image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-test
          TAG=${{github.sha}}
          docker build -t $IMAGE:$TAG .
      - name: Push image to Docker Hub
        run: |
          IMAGE=${ secrets.DOCKER_USERNAME }/ci-test
          TAG=${ github.sha }
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest