name: Build and push to Docker Hub
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & tag image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-test
          TAG=${{github.sha}}
          docker build -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest
      - name: Push image to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/ci-test
          TAG=${{ github.sha }}
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      
      - name: Apply Kubernetes manifests
        run: |
          set -e
          export GITHUB_SHA=${{ github.sha }}
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          kubectl rollout status deployment/ci-simple-app || (
            echo "Deployment failed, Attempting to roll back..."
            kubectl rollout undo deployment/ci-simple-app || echo "Rollback failed, please check the deployment manually."
            exit 1
          )
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml 